jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:sP'
            default_timezone: "UTC"
    expression_evaluator:
        id: jms_serializer.expression_evaluator