nelmio_api_doc:
    documentation:
        info:
            title: SOLID Symfony API
            description: This is an awesome example!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc)
